debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.study.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/board
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always

  data:
    rest:
      base-path: /api
      detection-strategy: annotated

server:
  port: 18088

---

spring:
  config:
    activate:
      on-profile:
        - testdb
  datasource:
    url: jdbc:h2:mem:board;mode=PostgreSQL
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  test:
    database:
      replace: none

