insert into article (title, content, hash_tag, created_by, modified_by, created_at, modified_at) values ('Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.

Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Fuscia', 'Amberly', 'Denise', '2021-11-18 04:15:34', '2022-03-15 05:43:35');
insert into article (title, content, hash_tag, created_by, modified_by, created_at, modified_at) values ('Duis mattis egestas metus.', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Fuscia', 'Catie', 'Fletch', '2022-01-25 23:23:51', '2021-12-17 15:43:55');
insert into article (title, content, hash_tag, created_by, modified_by, created_at, modified_at) values ('Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Turquoise', 'Honor', 'Estelle', '2021-09-30 03:42:01', '2021-09-30 11:40:07');
insert into article (title, content, hash_tag, created_by, modified_by, created_at, modified_at) values ('Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Yellow', 'Maud', 'Hoebart', '2021-08-01 22:55:15', '2022-03-27 00:08:54');
insert into article (title, content, hash_tag, created_by, modified_by, created_at, modified_at) values ('Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Puce', 'Arabel', 'Fawnia', '2021-11-02 00:28:47', '2021-07-18 19:11:09');


---
insert into article_comment (content, article_id, created_by, modified_by, created_at, modified_at) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, 'Archy', 'Gabriellia', '2021-09-07 02:42:44', '2022-05-28 18:51:09');
insert into article_comment (content, article_id, created_by, modified_by, created_at, modified_at) values ('Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 2, 'Anthia', 'Selby', '2022-03-23 23:44:39', '2021-08-21 21:47:18');
insert into article_comment (content, article_id, created_by, modified_by, created_at, modified_at) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 3, 'Amabelle', 'Caterina', '2021-12-19 20:03:49', '2022-07-06 21:01:21');
insert into article_comment (content, article_id, created_by, modified_by, created_at, modified_at) values ('Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 4, 'Dory', 'Drew', '2022-06-15 11:48:45', '2021-09-29 23:07:21');
insert into article_comment (content, article_id, created_by, modified_by, created_at, modified_at) values ('Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 5, 'Caitlin', 'Paolo', '2021-09-27 08:50:05', '2022-04-29 21:49:13');
